import { v4 as uuid } from "uuid";
import type { SSIIndex, SSIAssetWeight, SmartMoneyNewsletter } from "@bloom-ai/types";
import { getMarketSnapshots } from "../../services/sosovalue.js";
import { wsManager } from "../../ws/manager.js";
import { strategyStore } from "../../store/strategy.js";
import { signalLedger } from "../../store/signalLedger.js";
export { strategyStore };

export let strategistStatus: {
  status: "running" | "idle" | "error";
  lastRun: string | null;
  lastError: string | null;
  lastStrategyId: string | null;
  cycleCount: number;
} = { status: "idle", lastRun: null, lastError: null, lastStrategyId: null, cycleCount: 0 };

/**
 * Strategist Agent — portfolio generation and SSI index minting.
 *
 * Receives newsletter insights from the Journalist, translates the macro
 * narrative into optimal portfolio weights, and (in production) calls the
 * SSI Protocol to mint a bespoke Wrapped Token index.
 */
export async function runStrategistCycle(
  newsletter: SmartMoneyNewsletter,
): Promise<SSIIndex | null> {
  strategistStatus.status = "running";
  strategistStatus.lastError = null;
  try {
    console.log("[Strategist] Generating strategy for:", newsletter.narrative);

    // Fetch live prices to compute current weights
    const marketsResult = await getMarketSnapshots();
    const priceMap = Object.fromEntries(marketsResult.data.map(m => [m.symbol, m.price]));

    // Determine portfolio composition based on narrative
    const weights = deriveWeights(newsletter.narrative, newsletter.keyAssets);

    // Build asset list with live prices
    const assets: SSIAssetWeight[] = weights.map(({ symbol, weight }) => ({
      symbol,
      address: `0x${Buffer.from(symbol).toString("hex").padEnd(40, "0")}`,
      weight,
      currentPrice: priceMap[symbol] ?? 1,
    }));

    // Generate index name from narrative
    const indexName = `BLOOM-${newsletter.narrative.toUpperCase().replace("-", "")}-${Date.now().toString(36).toUpperCase()}`;

    const newStrategy: SSIIndex = {
      id: `ssi-${uuid().slice(0, 8)}`,
      name: indexName,
      symbol: `${indexName}.ssi`,
      description: `Auto-generated by Bloom AI Strategist agent based on "${newsletter.title}" narrative signal.`,
      assets,
      tvl: 0, // starts at 0 — grows as users copy
      dailyFee: 0.0001,
      createdAt: new Date().toISOString(),
      rebalancedAt: new Date().toISOString(),
    };

    strategyStore.add(newStrategy);

    const signal = signalLedger.recordSignal({
      source: "strategist",
      title: `SSI Index Created: ${newStrategy.symbol}`,
      summary: newStrategy.description,
      narrative: newsletter.narrative,
      keyAssets: newStrategy.assets.map((a) => a.symbol),
      newsletterId: newsletter.id,
      strategyId: newStrategy.id,
      evidence: newStrategy.assets.map((a) => ({
        source: "strategist",
        label: a.symbol,
        value: `${(a.weight * 100).toFixed(1)}% @ $${a.currentPrice}`,
        module: "computed" as const,
      })),
      inputData: { newsletterId: newsletter.id, narrative: newsletter.narrative },
      contentData: newStrategy,
    });
    signalLedger.linkStrategy(signal.id, newStrategy.id);
    newStrategy.signalId = signal.id;
    strategyStore.update(newStrategy.id, { signalId: signal.id });

    wsManager.broadcast({
      type: "STRATEGY_CREATED",
      payload: newStrategy,
      timestamp: new Date().toISOString(),
    });

    console.log(`[Strategist] Created strategy: ${newStrategy.symbol}`);
    strategistStatus.status = "idle";
    strategistStatus.lastRun = new Date().toISOString();
    strategistStatus.lastStrategyId = newStrategy.id;
    strategistStatus.cycleCount++;
    return newStrategy;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[Strategist] Cycle failed:", msg);
    strategistStatus.status = "error";
    strategistStatus.lastError = msg;
    return null;
  }
}

/** Derive portfolio weights from macro narrative */
function deriveWeights(
  narrative: SmartMoneyNewsletter["narrative"],
  keyAssets: string[],
): { symbol: string; weight: number }[] {
  const validAssets = ["BTC", "ETH", "SOL", "BNB", "LINK", "AVAX", "ARB"];

  switch (narrative) {
    case "risk-on":
      // Overweight high-beta: SOL, BTC, ETH
      return [
        { symbol: "BTC", weight: 0.35 },
        { symbol: "ETH", weight: 0.30 },
        { symbol: "SOL", weight: 0.35 },
      ];
    case "risk-off":
      // Shift to safety: BTC dominance, stablecoin buffer
      return [
        { symbol: "BTC", weight: 0.55 },
        { symbol: "ETH", weight: 0.25 },
        { symbol: "LINK", weight: 0.20 },
      ];
    case "rotation":
      // Narrative-specific: weight keyAssets heavily
      return (
        keyAssets
          .filter(a => validAssets.includes(a))
          .slice(0, 4)
          .map((asset, i, arr) => ({
            symbol: asset,
            weight: parseFloat((1 / arr.length).toFixed(2)),
          })) || [{ symbol: "BTC", weight: 0.5 }, { symbol: "ETH", weight: 0.5 }]
      );
    default:
      return [
        { symbol: "BTC", weight: 0.50 },
        { symbol: "ETH", weight: 0.50 },
      ];
  }
}
