import { v4 as uuid } from "uuid";
import type { SSIIndex, SSIAssetWeight, SmartMoneyNewsletter } from "@bloom-ai/types";
import { getMarketSnapshots } from "../../services/sosovalue.js";
import { wsManager } from "../../ws/manager.js";

// In-memory strategy store — production: persist to Postgres + SSI contracts
class StrategyStore {
  private strategies: SSIIndex[] = [
    {
      id: "ssi-rwa-001",
      name: "BLOOM-RWA",
      symbol: "BLOOM-RWA.ssi",
      description:
        "AI-curated Real World Asset index. Overweights tokenised T-bills, real estate tokens, and institutional-grade stablecoins based on macro rotation signals.",
      assets: [
        { symbol: "BTC", address: "0x0000000000000000000000000000000000000001", weight: 0.35, currentPrice: 68420 },
        { symbol: "ETH", address: "0x0000000000000000000000000000000000000002", weight: 0.25, currentPrice: 3812 },
        { symbol: "USDC", address: "0x0000000000000000000000000000000000000003", weight: 0.20, currentPrice: 1.00 },
        { symbol: "LINK", address: "0x0000000000000000000000000000000000000004", weight: 0.20, currentPrice: 17.83 },
      ],
      tvl: 8_400_000,
      dailyFee: 0.0001,
      createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      rebalancedAt: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      id: "ssi-defi-002",
      name: "BLOOM-DEFI",
      symbol: "BLOOM-DEFI.ssi",
      description:
        "High-beta DeFi protocol basket. Tracks top revenue-generating protocols with dynamic weighting based on 30-day protocol fee growth.",
      assets: [
        { symbol: "ETH", address: "0x0000000000000000000000000000000000000002", weight: 0.40, currentPrice: 3812 },
        { symbol: "BTC", address: "0x0000000000000000000000000000000000000001", weight: 0.30, currentPrice: 68420 },
        { symbol: "SOL", address: "0x0000000000000000000000000000000000000005", weight: 0.30, currentPrice: 182.4 },
      ],
      tvl: 5_200_000,
      dailyFee: 0.0001,
      createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
      rebalancedAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: "ssi-mag7-003",
      name: "BLOOM-MAG7",
      symbol: "BLOOM-MAG7.ssi",
      description:
        "Crypto's magnificent seven — top 7 assets by institutional adoption and ETF inflows. Auto-rebalances when ETF flow dominance shifts.",
      assets: [
        { symbol: "BTC", address: "0x0000000000000000000000000000000000000001", weight: 0.35, currentPrice: 68420 },
        { symbol: "ETH", address: "0x0000000000000000000000000000000000000002", weight: 0.25, currentPrice: 3812 },
        { symbol: "SOL", address: "0x0000000000000000000000000000000000000005", weight: 0.40, currentPrice: 182.4 },
      ],
      tvl: 14_700_000,
      dailyFee: 0.0001,
      createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
      rebalancedAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ];

  getAll(): SSIIndex[] { return this.strategies; }
  getById(id: string): SSIIndex | undefined { return this.strategies.find(s => s.id === id); }

  add(strategy: SSIIndex) {
    this.strategies.unshift(strategy);
  }

  updateTVL(id: string, tvl: number) {
    const s = this.strategies.find(s => s.id === id);
    if (s) s.tvl = tvl;
  }
}

export const strategyStore = new StrategyStore();

/**
 * Strategist Agent — portfolio generation and SSI index minting.
 *
 * Receives newsletter insights from the Journalist, translates the macro
 * narrative into optimal portfolio weights, and (in production) calls the
 * SSI Protocol to mint a bespoke Wrapped Token index.
 */
export async function runStrategistCycle(
  newsletter: SmartMoneyNewsletter,
): Promise<SSIIndex | null> {
  try {
    console.log("[Strategist] Generating strategy for:", newsletter.narrative);

    // Fetch live prices to compute current weights
    const marketsResult = await getMarketSnapshots();
    const priceMap = Object.fromEntries(marketsResult.data.map(m => [m.symbol, m.price]));

    // Determine portfolio composition based on narrative
    const weights = deriveWeights(newsletter.narrative, newsletter.keyAssets);

    // Build asset list with live prices
    const assets: SSIAssetWeight[] = weights.map(({ symbol, weight }) => ({
      symbol,
      address: `0x${Buffer.from(symbol).toString("hex").padEnd(40, "0")}`,
      weight,
      currentPrice: priceMap[symbol] ?? 1,
    }));

    // Generate index name from narrative
    const indexName = `BLOOM-${newsletter.narrative.toUpperCase().replace("-", "")}-${Date.now().toString(36).toUpperCase()}`;

    const newStrategy: SSIIndex = {
      id: `ssi-${uuid().slice(0, 8)}`,
      name: indexName,
      symbol: `${indexName}.ssi`,
      description: `Auto-generated by Bloom AI Strategist agent based on "${newsletter.title}" narrative signal.`,
      assets,
      tvl: 0, // starts at 0 — grows as users copy
      dailyFee: 0.0001,
      createdAt: new Date().toISOString(),
      rebalancedAt: new Date().toISOString(),
    };

    strategyStore.add(newStrategy);

    wsManager.broadcast({
      type: "STRATEGY_CREATED",
      payload: newStrategy,
      timestamp: new Date().toISOString(),
    });

    console.log(`[Strategist] Created strategy: ${newStrategy.symbol}`);
    return newStrategy;
  } catch (err) {
    console.error("[Strategist] Cycle failed:", err);
    return null;
  }
}

/** Derive portfolio weights from macro narrative */
function deriveWeights(
  narrative: SmartMoneyNewsletter["narrative"],
  keyAssets: string[],
): { symbol: string; weight: number }[] {
  const validAssets = ["BTC", "ETH", "SOL", "BNB", "LINK", "AVAX", "ARB"];

  switch (narrative) {
    case "risk-on":
      // Overweight high-beta: SOL, BTC, ETH
      return [
        { symbol: "BTC", weight: 0.35 },
        { symbol: "ETH", weight: 0.30 },
        { symbol: "SOL", weight: 0.35 },
      ];
    case "risk-off":
      // Shift to safety: BTC dominance, stablecoin buffer
      return [
        { symbol: "BTC", weight: 0.55 },
        { symbol: "ETH", weight: 0.25 },
        { symbol: "LINK", weight: 0.20 },
      ];
    case "rotation":
      // Narrative-specific: weight keyAssets heavily
      return (
        keyAssets
          .filter(a => validAssets.includes(a))
          .slice(0, 4)
          .map((asset, i, arr) => ({
            symbol: asset,
            weight: parseFloat((1 / arr.length).toFixed(2)),
          })) || [{ symbol: "BTC", weight: 0.5 }, { symbol: "ETH", weight: 0.5 }]
      );
    default:
      return [
        { symbol: "BTC", weight: 0.50 },
        { symbol: "ETH", weight: 0.50 },
      ];
  }
}
